name: Deploy via FTP

on:
  push:
    branches:
      - main # Sesuaikan jika branch kamu bernama 'master'

jobs:
  web-deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Mengekstrak Kode Terbaru
        uses: actions/checkout@v3

      - name: ⚙️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Sesuaikan dengan versi PHP kamu

      - name: 📦 Install Dependensi (Composer)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: 🌐 Sinkronisasi File via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22 # Ubah angka 22 jika provider hostingmu menggunakan port SSH khusus
          remote_path: '/public_html/'
          sftp_only: true
          # Tetap mengecualikan folder berukuran besar agar cepat
          args: '--exclude .git/ --exclude node_modules/ --exclude vendor/ --exclude .env'