name: Deploy via FTP

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Mengekstrak Kode Terbaru
        uses: actions/checkout@v3

      - name: ⚙️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' 

      - name: 📦 Install Dependensi (Composer)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # -------------------------------------------------------------
      # LANGKAH BARU: Hapus folder berat sebelum dikirim ke cPanel
      # -------------------------------------------------------------
      - name: 🧹 Hapus folder berat agar tidak ikut dikirim via SFTP
        run: rm -rf vendor node_modules .git

      - name: 🌐 Sinkronisasi File via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22 
          remote_path: 'public_html/'
          sftp_only: true
          # Args tetap disertakan sebagai lapisan keamanan tambahan
          args: '--exclude .git/ --exclude node_modules/ --exclude vendor/ --exclude .env'